-- Pismai production save queue.
-- Additive only: this migration does not modify or delete existing production records.

alter table public.production_records
  add column if not exists queue_dedupe_key text;

create unique index if not exists production_records_queue_dedupe_key_unique
  on public.production_records(queue_dedupe_key)
  where queue_dedupe_key is not null;

create table if not exists public.production_save_queue (
  id bigint generated by default as identity primary key,
  queue_uid text not null,
  batch_uid text,
  payload jsonb not null,
  payload_hash text not null,
  record_count integer not null,
  fruit_type text not null,
  record_date date not null,
  employee_id bigint,
  emp_code text not null,
  employee_name text not null default '',
  total_weight numeric(14,3) not null default 0,
  total_amount numeric(14,2) not null default 0,
  status text not null default 'queued',
  attempt_count integer not null default 0,
  max_attempts integer not null default 3,
  next_attempt_at timestamptz not null default now(),
  locked_at timestamptz,
  locked_by text,
  started_at timestamptz,
  finished_at timestamptz,
  result_record_ids bigint[] not null default '{}',
  result_payload jsonb not null default '[]'::jsonb,
  duplicate_details jsonb not null default '{}'::jsonb,
  error_code text,
  error_message text,
  created_by text not null,
  cancelled_by text,
  cancelled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint production_save_queue_uid_unique unique (queue_uid),
  constraint production_save_queue_payload_array check (jsonb_typeof(payload) = 'array'),
  constraint production_save_queue_record_count check (record_count between 1 and 100),
  constraint production_save_queue_status_check check (
    status in ('queued', 'processing', 'succeeded', 'needs_review', 'failed', 'cancelled')
  ),
  constraint production_save_queue_attempt_check check (
    attempt_count >= 0 and max_attempts between 1 and 10
  )
);

create index if not exists idx_production_save_queue_work
  on public.production_save_queue(status, next_attempt_at, id);
create index if not exists idx_production_save_queue_created
  on public.production_save_queue(created_at desc);
create index if not exists idx_production_save_queue_employee
  on public.production_save_queue(record_date, emp_code, fruit_type);
create index if not exists idx_production_save_queue_creator
  on public.production_save_queue(created_by, created_at desc);

create table if not exists public.production_save_queue_events (
  id bigint generated by default as identity primary key,
  queue_id bigint not null references public.production_save_queue(id) on delete restrict,
  event_type text not null,
  status text not null,
  message text,
  actor text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_production_save_queue_events_queue
  on public.production_save_queue_events(queue_id, created_at asc, id asc);

create or replace function public.set_production_save_queue_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_production_save_queue_updated_at on public.production_save_queue;
create trigger trg_production_save_queue_updated_at
before update on public.production_save_queue
for each row execute function public.set_production_save_queue_updated_at();

create or replace function public.claim_next_production_save_queue(p_worker_id text)
returns setof public.production_save_queue
language plpgsql
security definer
set search_path = public
as $$
declare
  claimed_id bigint;
begin
  -- A Render restart must not leave a job permanently locked. Five minutes
  -- also prevents a slow in-flight request from being claimed by two workers.
  update public.production_save_queue
  set status = 'queued',
      locked_at = null,
      locked_by = null,
      next_attempt_at = now(),
      error_code = 'stale_worker_recovered',
      error_message = 'Recovered after the previous worker stopped responding.'
  where status = 'processing'
    and locked_at < now() - interval '5 minutes';

  select id into claimed_id
  from public.production_save_queue
  where status = 'queued'
    and next_attempt_at <= now()
    and attempt_count < max_attempts
  order by id asc
  for update skip locked
  limit 1;

  if claimed_id is null then
    return;
  end if;

  return query
  update public.production_save_queue
  set status = 'processing',
      attempt_count = attempt_count + 1,
      locked_at = now(),
      locked_by = nullif(trim(p_worker_id), ''),
      started_at = coalesce(started_at, now()),
      error_code = null,
      error_message = null
  where id = claimed_id
  returning *;
end;
$$;

alter table public.production_save_queue enable row level security;
alter table public.production_save_queue_events enable row level security;

grant select, insert, update on public.production_save_queue to service_role;
grant usage, select on sequence public.production_save_queue_id_seq to service_role;
grant select, insert on public.production_save_queue_events to service_role;
grant usage, select on sequence public.production_save_queue_events_id_seq to service_role;
revoke all on function public.claim_next_production_save_queue(text) from public;
revoke all on function public.claim_next_production_save_queue(text) from anon;
revoke all on function public.claim_next_production_save_queue(text) from authenticated;
grant execute on function public.claim_next_production_save_queue(text) to service_role;
