-- Pismai time-record save queue.
-- Additive only: existing time records are not changed or deleted.

alter table public.time_records
  add column if not exists queue_dedupe_key text;

create unique index if not exists time_records_queue_dedupe_key_unique
  on public.time_records(queue_dedupe_key)
  where queue_dedupe_key is not null;

create table if not exists public.time_save_queue (
  id bigint generated by default as identity primary key,
  queue_uid text not null unique,
  operation text not null default 'insert',
  payload jsonb not null,
  payload_hash text not null,
  record_count integer not null,
  emp_code text not null,
  employee_name text not null default '',
  first_work_date date not null,
  last_work_date date not null,
  status text not null default 'queued',
  attempt_count integer not null default 0,
  max_attempts integer not null default 3,
  next_attempt_at timestamptz not null default now(),
  locked_at timestamptz,
  locked_by text,
  started_at timestamptz,
  finished_at timestamptz,
  result_record_ids bigint[] not null default '{}',
  result_payload jsonb not null default '[]'::jsonb,
  error_code text,
  error_message text,
  created_by text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint time_save_queue_operation_check check (operation in ('insert', 'update')),
  constraint time_save_queue_payload_array check (jsonb_typeof(payload) = 'array'),
  constraint time_save_queue_record_count check (record_count between 1 and 31),
  constraint time_save_queue_status_check check (
    status in ('queued', 'processing', 'succeeded', 'needs_review', 'failed')
  ),
  constraint time_save_queue_attempt_check check (attempt_count >= 0 and max_attempts between 1 and 10)
);

create index if not exists idx_time_save_queue_work
  on public.time_save_queue(status, next_attempt_at, id);
create index if not exists idx_time_save_queue_created
  on public.time_save_queue(created_at desc);
create index if not exists idx_time_save_queue_employee
  on public.time_save_queue(emp_code, first_work_date, last_work_date);

create table if not exists public.time_save_queue_events (
  id bigint generated by default as identity primary key,
  queue_id bigint not null references public.time_save_queue(id) on delete restrict,
  event_type text not null,
  status text not null,
  message text,
  actor text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_time_save_queue_events_queue
  on public.time_save_queue_events(queue_id, created_at asc, id asc);

create or replace function public.set_time_save_queue_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_time_save_queue_updated_at on public.time_save_queue;
create trigger trg_time_save_queue_updated_at
before update on public.time_save_queue
for each row execute function public.set_time_save_queue_updated_at();

create or replace function public.claim_next_time_save_queue(p_worker_id text)
returns setof public.time_save_queue
language plpgsql security definer set search_path = public as $$
declare claimed_id bigint;
begin
  update public.time_save_queue
  set status = 'queued', locked_at = null, locked_by = null,
      next_attempt_at = now(), error_code = 'stale_worker_recovered',
      error_message = 'Recovered after the previous worker stopped responding.'
  where status = 'processing' and locked_at < now() - interval '5 minutes';

  select id into claimed_id
  from public.time_save_queue
  where status = 'queued' and next_attempt_at <= now() and attempt_count < max_attempts
  order by id asc for update skip locked limit 1;

  if claimed_id is null then return; end if;

  return query
  update public.time_save_queue
  set status = 'processing', attempt_count = attempt_count + 1,
      locked_at = now(), locked_by = nullif(trim(p_worker_id), ''),
      started_at = coalesce(started_at, now()), error_code = null, error_message = null
  where id = claimed_id returning *;
end;
$$;

alter table public.time_save_queue enable row level security;
alter table public.time_save_queue_events enable row level security;
grant select, insert, update on public.time_save_queue to service_role;
grant usage, select on sequence public.time_save_queue_id_seq to service_role;
grant select, insert on public.time_save_queue_events to service_role;
grant usage, select on sequence public.time_save_queue_events_id_seq to service_role;
revoke all on function public.claim_next_time_save_queue(text) from public, anon, authenticated;
grant execute on function public.claim_next_time_save_queue(text) to service_role;
