-- Inbound fruit purchasing: master fruit, recommended-price history, and immutable receipt snapshots.
create table if not exists public.inbound_fruits (
  id bigint generated by default as identity primary key,
  name text not null,
  normalized_name text not null unique,
  status text not null default 'Active' check (status in ('Active', 'Inactive')),
  created_by text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.inbound_fruit_prices (
  id bigint generated by default as identity primary key,
  fruit_id bigint not null references public.inbound_fruits(id) on delete restrict,
  price_per_kg numeric(12,2) not null check (price_per_kg > 0),
  effective_date date not null,
  note text not null default '',
  created_by text not null,
  created_at timestamptz not null default now(),
  unique (fruit_id, effective_date, created_at)
);

create table if not exists public.inbound_receipts (
  id bigint generated by default as identity primary key,
  client_uid text not null unique,
  received_at timestamptz not null,
  supplier_name text not null,
  fruit_id bigint not null references public.inbound_fruits(id) on delete restrict,
  fruit_name text not null,
  weight_kg numeric(14,2) not null check (weight_kg > 0),
  price_per_kg numeric(12,2) not null check (price_per_kg > 0),
  total_amount numeric(16,2) not null check (total_amount >= 0),
  note text not null default '',
  created_by text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_inbound_prices_fruit_effective on public.inbound_fruit_prices(fruit_id, effective_date desc, created_at desc);
create index if not exists idx_inbound_receipts_received_at on public.inbound_receipts(received_at desc);
create index if not exists idx_inbound_receipts_supplier on public.inbound_receipts(supplier_name);
create index if not exists idx_inbound_receipts_fruit on public.inbound_receipts(fruit_id);

alter table public.inbound_fruits enable row level security;
alter table public.inbound_fruit_prices enable row level security;
alter table public.inbound_receipts enable row level security;

-- The web server uses the Supabase service role and performs session/level checks.
revoke all on public.inbound_fruits from anon, authenticated;
revoke all on public.inbound_fruit_prices from anon, authenticated;
revoke all on public.inbound_receipts from anon, authenticated;

