-- PF Accounting: weekly cash / bank-transfer allocation.
-- Safe to run more than once in Supabase SQL Editor.

create table if not exists public.ac_payment_allocations (
  id bigint generated by default as identity primary key,
  company_key text not null default 'pismai-main',
  week_start date not null,
  week_end date not null,
  employee_key text not null,
  employee_kind text not null check (employee_kind in ('production', 'time')),
  employee_id text,
  emp_code text not null,
  fullname text not null,
  group_label text not null,
  payment_method text not null check (payment_method in ('cash', 'transfer')),
  net_amount numeric(14,2) not null default 0 check (net_amount >= 0),
  updated_by text not null,
  updated_at timestamptz not null default now(),
  constraint ac_payment_allocations_valid_week check (week_start <= week_end),
  constraint ac_payment_allocations_unique_employee_week unique (company_key, week_start, week_end, employee_key)
);

create index if not exists idx_ac_payment_allocations_week
  on public.ac_payment_allocations(company_key, week_start desc, week_end desc, payment_method);

alter table public.ac_payment_allocations enable row level security;
revoke all on public.ac_payment_allocations from anon, authenticated;
grant select, insert, update, delete on public.ac_payment_allocations to service_role;
grant usage, select on sequence public.ac_payment_allocations_id_seq to service_role;

create or replace function public.ac_payment_touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_ac_payment_touch_updated_at on public.ac_payment_allocations;
create trigger trg_ac_payment_touch_updated_at
before update on public.ac_payment_allocations
for each row execute function public.ac_payment_touch_updated_at();
